version: "3.9"

volumes:
  db_data:
    driver: local

services:
  db:
    image: postgres
    container_name: book-store-postgres
    volumes:
      - db_data:/var/lib/postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  api:
    build: .
    container_name: book-store-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bookstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db